[build]
  command = "bun install && bun run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/track/*"
  to = "/.netlify/functions/api/track/:splat"
  status = 200

[[redirects]]
  from = "/sent-emails"
  to = "/.netlify/functions/api/sent-emails"
  status = 200

[[redirects]]
  from = "/send-resume"
  to = "/.netlify/functions/api/send-resume"
  status = 200

[[redirects]]
  from = "/gemini/generate"
  to = "/.netlify/functions/api/gemini/generate"
  status = 200

[[redirects]]
  from = "/auth/gmail"
  to = "/.netlify/functions/api/auth/gmail"
  status = 200

[[redirects]]
  from = "/oauth2callback"
  to = "/.netlify/functions/api/oauth2callback"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/.netlify/functions/api/dashboard"
  status = 200

[[redirects]]
  from = "/tinder"
  to = "/.netlify/functions/api/tinder"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 